export const initialProduct = {
  count: 0,
  description: "",
  filters: [],
  next: "",
  nofollow: false,
  nofollow_collections: [],
  noindex: false,
  previous: null,
  results: [],
  seo_description: "",
  seo_h1: "",
  seo_keyword: "",
  seo_title: "",
};
